from __future__ import annotations

# Operational storage retention and query bounds.
AGENT_TASK_LIST_DEFAULT_LIMIT = 20
AGENT_TASK_LIST_MAX_LIMIT = 100
AGENT_TASK_EVENT_LIST_DEFAULT_LIMIT = 200
AGENT_TASK_EVENT_LIST_MAX_LIMIT = 500
AGENT_TASK_EVENT_RETENTION_COUNT = 200
AGENT_TASK_RECEIPT_LIST_LIMIT = 112
AGENT_TASK_RECEIPT_RETENTION_COUNTS = {
    "summary": 64,
    "diagnostic": 32,
    "trace": 16,
}
AGENT_TASK_ESTIMATE_HISTORY_LIMIT = 100
AGENT_TASK_ESTIMATE_SAMPLE_LIMIT = 20
AGENT_TASK_RECEIPT_MAX_BYTES = 8 * 1024
AGENT_TASK_RESULT_MAX_BYTES = 64 * 1024
PATCH_OUTPUT_RETENTION_DAYS = 7
RUN_TRACE_RETENTION_DAYS = 90
WRITING_SESSION_RETENTION_DAYS = 180
WRITING_SESSIONS_PER_PROJECT = 50

# Durable canonical chat history queries and summary labels.
CHAT_PAGE_DEFAULT_LIMIT = 50
CHAT_PAGE_MAX_LIMIT = 200
CHAT_TITLE_MAX_CHARS = 120
CHAT_PREVIEW_MAX_CHARS = 240

# Temporary agent-created preview artifacts.
CHAT_ARTIFACT_MAX_COUNT = 8
CHAT_ARTIFACT_MAX_FILE_BYTES = 16 * 1024 * 1024
CHAT_ARTIFACT_MAX_TOTAL_BYTES = 32 * 1024 * 1024
# Temporary human-provided chat inputs. Keep these independent from output artifact
# limits even while their initial bounds happen to be the same.
CHAT_ATTACHMENT_MAX_COUNT = 8
CHAT_ATTACHMENT_MAX_FILE_BYTES = 16 * 1024 * 1024
CHAT_ATTACHMENT_MAX_TOTAL_BYTES = 32 * 1024 * 1024
RUN_STAGE_RETENTION_DAYS = 7
REMOTE_ARTIFACT_READ_TIMEOUT_SECONDS = 30

# Live patch self-validation through the run-stage file mailbox.
PATCH_SELF_CHECK_MAX_COUNT = 6
PATCH_SELF_CHECK_POLL_SECONDS = 0.2
PATCH_SELF_CHECK_TIMEOUT_SECONDS = 30
PATCH_SELF_CHECK_MAX_REQUEST_BYTES = 16 * 1024 * 1024

# Durable external-work watchers.
WATCHER_CHECK_TIMEOUT_SECONDS = 15
WATCHER_POLL_INTERVAL_SECONDS = 5
ACCEPTANCE_AGENT_JOB_SECONDS = 2.0
WATCHER_CHECK_WORKERS = 4
WATCHER_ERROR_MAX_CHARS = 4000
WATCHER_HEALTHY_INTERVAL_SECONDS = 2 * 60
WATCHER_ERROR_BACKOFF_SECONDS = (2 * 60, 4 * 60, 8 * 60, 15 * 60, 30 * 60)
WATCHER_SCHEDULE_JITTER_RATIO = 0.10
WATCHER_GROUP_DIAGNOSTIC_ERROR_COUNT = 5

# Agent context budgets.
CHAT_CONVERSATION_LIMIT = 120
RUN_INLINE_SESSION_LIMIT = 40
RUN_INLINE_SESSION_BYTES = 12 * 1024
REFRESH_DELTA_MAX_ENTRIES = 50
REFRESH_DELTA_MAX_BYTES = 16 * 1024

# Rebuildable display/source caches and remote source operations.
PROJECT_DISPLAY_SNAPSHOT_MAX_BYTES = 16 * 1024 * 1024
REMOTE_SOURCE_CACHE_TTL_SECONDS = 30 * 24 * 60 * 60
REMOTE_SOURCE_CACHE_MAX_COUNT = 256
REMOTE_SOURCE_CACHE_MAX_BYTES = 1024 * 1024 * 1024
SESSION_SLICE_CACHE_TTL_SECONDS = 14 * 24 * 60 * 60
SESSION_SLICE_CACHE_MAX_COUNT = 512
SESSION_SLICE_CACHE_MAX_BYTES = 512 * 1024 * 1024
REMOTE_SOURCE_OPERATION_TIMEOUT_SECONDS = 180

# Canonical-state advisory lock acquisition and holder lifecycle.
STATE_LOCK_ATTEMPT_TIMEOUT_SECONDS = 30.0
STATE_LOCK_HOLDER_STOP_TIMEOUT_SECONDS = 5.0
STATE_LOCK_POLL_INTERVAL_SECONDS = 0.2

# Server and frontend-build lifecycle timings.
SERVER_SHUTDOWN_TIMEOUT_SECONDS = 15.0
SERVER_LOCK_DEFAULT_TIMEOUT_SECONDS = 0.0
SERVER_LOCK_OWNER_READ_ATTEMPTS = 10
SERVER_LOCK_POLL_INTERVAL_SECONDS = 0.05
SERVER_HEALTH_REQUEST_TIMEOUT_SECONDS = 2
BROWSER_OPEN_DELAY_SECONDS = 0.7
WEB_BUILD_TIMEOUT_SECONDS = 60.0
WEB_BUILD_STOP_TIMEOUT_SECONDS = 5.0
WEB_BUILD_POLL_INTERVAL_SECONDS = 0.05
