use std::{path::Path, process::Command};

/// The RCP window loads the backend's own origin, which the ACL treats as remote,
/// so every app command needs an autogenerated permission the capability can grant.
const COMMANDS: &[&str] = &[
    "desktop_status",
    "desktop_reconnect_backend",
    "desktop_show_ready",
    "desktop_list_team_connections",
    "desktop_configure_server_operator_route",
    "desktop_probe_server_operator",
    "desktop_run_project_provision",
    "desktop_open_project_provision_terminal",
    "desktop_run_project_transfer",
    "desktop_prepare_project_transfer",
    "desktop_load_project_transfer",
    "desktop_advance_project_transfer",
    "desktop_run_incoming_project_provision",
    "desktop_read_target_project_provisioning_options",
    "desktop_export_project_transfer",
    "desktop_select_project_transfer_export",
    "desktop_open_project_transfer_terminal",
    "desktop_finish_project_transfer",
    "desktop_discard_project_transfer_export",
    "desktop_remove_team_connection_metadata",
    "desktop_remove_team_member_token",
    "desktop_connect_team_tunnel",
    "desktop_enroll_team_connection",
    "desktop_add_existing_team_connection",
    "desktop_establish_team_session",
    "desktop_navigate_team",
    "desktop_return_to_personal",
    "choose_repository_folder",
    "desktop_start_dictation",
    "desktop_stop_dictation",
    "open_artifact_preview",
    "open_episode_report_preview",
    "open_repository_file_preview",
    "download_artifact",
    "open_external",
    "request_quit",
    "check_for_update",
    "apply_update",
];

fn main() {
    embed_source_commit();
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("macos") {
        cc::Build::new()
            .file("src/dictation.m")
            .flag("-fobjc-arc")
            .flag("-fblocks")
            .compile("rcp_dictation");
        println!("cargo:rustc-link-lib=framework=AVFoundation");
        println!("cargo:rustc-link-lib=framework=Foundation");
        println!("cargo:rustc-link-lib=framework=Speech");
        println!("cargo:rerun-if-changed=src/dictation.m");
        cc::Build::new()
            .file("src/https_trust.m")
            .flag("-fobjc-arc")
            .flag("-fblocks")
            .compile("rcp_https_trust");
        println!("cargo:rustc-link-lib=framework=Security");
        println!("cargo:rerun-if-changed=src/https_trust.m");
    }
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("failed to run tauri-build");
}

fn embed_source_commit() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
        .expect("Cargo must provide the desktop manifest directory");
    let repository = Path::new(&manifest_dir).join("../..");
    let output = Command::new("git")
        .args(["rev-parse", "HEAD"])
        .current_dir(&repository)
        .output()
        .expect("the source-built desktop requires Git");
    let commit = String::from_utf8(output.stdout)
        .expect("Git returned a non-UTF-8 source commit")
        .trim()
        .to_string();
    if !output.status.success()
        || commit.len() != 40
        || !commit
            .bytes()
            .all(|byte| byte.is_ascii_digit() || matches!(byte, b'a'..=b'f'))
    {
        panic!("the source-built desktop requires one exact lowercase Git commit");
    }
    println!("cargo:rustc-env=RCP_DESKTOP_SOURCE_COMMIT={commit}");
    println!("cargo:rerun-if-changed=build.rs");

    let mut git_paths = vec!["HEAD".to_string(), "packed-refs".to_string()];
    let symbolic_ref = Command::new("git")
        .args(["symbolic-ref", "-q", "HEAD"])
        .current_dir(&repository)
        .output()
        .expect("the source-built desktop requires Git metadata");
    if symbolic_ref.status.success() {
        git_paths.push(
            String::from_utf8(symbolic_ref.stdout)
                .expect("Git returned a non-UTF-8 source ref")
                .trim()
                .to_string(),
        );
    }
    for git_path in git_paths {
        let path = Command::new("git")
            .args(["rev-parse", "--git-path", &git_path])
            .current_dir(&repository)
            .output()
            .expect("the source-built desktop requires Git metadata");
        if path.status.success() {
            let path = String::from_utf8(path.stdout)
                .expect("Git returned a non-UTF-8 metadata path")
                .trim()
                .to_string();
            println!("cargo:rerun-if-changed={path}");
        }
    }
}
