use std::{path::Path, process::Command};

/// The RCP window loads the backend's own origin, which the ACL treats as remote,
/// so every app command needs an autogenerated permission the capability can grant.
const COMMANDS: &[&str] = &[
    "desktop_status",
    "desktop_owner_sign_in",
    "desktop_reconnect_backend",
    "desktop_show_ready",
    "desktop_build_identity",
    "desktop_list_team_connections",
    "desktop_configure_server_operator_route",
    "desktop_probe_server_operator",
    "desktop_run_project_provision",
    "desktop_open_project_provision_terminal",
    "desktop_run_project_transfer",
    "desktop_prepare_project_transfer",
    "desktop_load_project_transfer",
    "desktop_advance_project_transfer",
    "desktop_run_incoming_project_provision",
    "desktop_read_target_project_provisioning_options",
    "desktop_export_project_transfer",
    "desktop_select_project_transfer_export",
    "desktop_open_project_transfer_terminal",
    "desktop_finish_project_transfer",
    "desktop_discard_project_transfer_export",
    "desktop_remove_team_connection_metadata",
    "desktop_remove_team_member_token",
    "desktop_connect_team_tunnel",
    "desktop_enroll_team_connection",
    "desktop_add_existing_team_connection",
    "desktop_establish_team_session",
    "desktop_navigate_team",
    "desktop_return_to_personal",
    "choose_repository_folder",
    "desktop_start_dictation",
    "desktop_stop_dictation",
    "desktop_keeps_voice_while_hidden",
    "desktop_notifications_enabled",
    "desktop_set_notifications",
    "desktop_test_notification",
    "open_artifact_pdf",
    "download_artifact",
    "open_external",
    "request_quit",
    "check_for_update",
    "apply_update",
];

fn main() {
    embed_source_commit();
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("macos") {
        let analyzer = build_speech_analyzer();
        let mut dictation = cc::Build::new();
        if analyzer {
            dictation.define("RCP_SPEECH_ANALYZER", None);
        }
        dictation
            .file("src/dictation.m")
            .flag("-fobjc-arc")
            .flag("-fblocks")
            .compile("rcp_dictation");
        println!("cargo:rustc-link-lib=framework=AVFoundation");
        println!("cargo:rustc-link-lib=framework=Foundation");
        println!("cargo:rustc-link-lib=framework=Speech");
        println!("cargo:rerun-if-changed=src/dictation.m");
        cc::Build::new()
            .file("src/https_trust.m")
            .flag("-fobjc-arc")
            .flag("-fblocks")
            .compile("rcp_https_trust");
        println!("cargo:rustc-link-lib=framework=Security");
        println!("cargo:rerun-if-changed=src/https_trust.m");
        cc::Build::new()
            .file("src/notifications.m")
            .flag("-fobjc-arc")
            .flag("-fblocks")
            .compile("rcp_notifications");
        println!("cargo:rustc-link-lib=framework=UserNotifications");
        println!("cargo:rerun-if-changed=src/notifications.m");
    }
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("failed to run tauri-build");
}

// Keep Swift out of older-SDK builds entirely: their Speech module has no analyzer API.
fn build_speech_analyzer() -> bool {
    for name in ["SDKROOT", "DEVELOPER_DIR", "RCP_REQUIRE_SPEECH_ANALYZER"] {
        println!("cargo:rerun-if-env-changed={name}");
    }
    println!("cargo:rerun-if-changed=src/dictation.swift");
    let sdk = std::env::var("SDKROOT").unwrap_or_else(|_| xcrun(&["--show-sdk-path"]));
    let version = xcrun(&["--sdk", &sdk, "--show-sdk-version"]);
    let major: u32 = version
        .split('.')
        .next()
        .unwrap()
        .parse()
        .expect("SDK version");
    if major < 26 {
        assert!(
            std::env::var("RCP_REQUIRE_SPEECH_ANALYZER").as_deref() != Ok("1"),
            "SpeechAnalyzer requires macOS SDK 26 or later; found {version}"
        );
        println!("cargo:warning=macOS SDK {version}: skipping SpeechAnalyzer; dictation uses the Apple server recognizer");
        return false;
    }
    let out = std::path::PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR"));
    let object = out.join("dictation_swift.o");
    let swiftc = xcrun(&["--find", "swiftc"]);
    let libraries = Path::new(&swiftc)
        .parent()
        .unwrap()
        .join("../lib/swift/macosx");
    let status = Command::new(&swiftc)
        .args([
            "-parse-as-library",
            "-emit-object",
            "-O",
            "-swift-version",
            "5",
            "-target",
            "arm64-apple-macos13.0",
            "-sdk",
            &sdk,
            "-module-name",
            "RCPDictation",
            "-module-cache-path",
        ])
        .arg(out.join("swift-module-cache"))
        .arg("src/dictation.swift")
        .arg("-o")
        .arg(&object)
        .status()
        .expect("run swiftc");
    assert!(status.success(), "Swift dictation compilation failed");
    cc::Build::new().object(&object).compile("rcp_analyzer");
    println!("cargo:rustc-link-search=native={}", libraries.display());
    println!("cargo:rustc-link-search=native={sdk}/usr/lib/swift");
    println!("cargo:rustc-link-arg=-Wl,-rpath,/usr/lib/swift");
    // swiftc normally supplies the compatibility archives at link time. Rust
    // owns our final link, so supply the toolchain's archives here instead.
    for entry in std::fs::read_dir(&libraries).expect("Swift libraries") {
        let path = entry.expect("Swift library").path();
        let name = path.file_name().unwrap().to_string_lossy();
        if name.starts_with("libswiftCompatibility") && name.ends_with(".a") {
            println!("cargo:rustc-link-lib=static={}", &name[3..name.len() - 2]);
        }
    }
    // Override Swift's autolink requests with weak loads. In particular, the
    // Speech overlay does not exist on macOS 13, even though Speech.framework does.
    let output = Command::new("xcrun")
        .args(["otool", "-l"])
        .arg(&object)
        .output()
        .expect("inspect Swift autolinks");
    assert!(output.status.success(), "could not inspect Swift autolinks");
    let loads = String::from_utf8(output.stdout).expect("otool output");
    let mut overlays = std::collections::BTreeSet::new();
    for line in loads.lines() {
        if let Some((_, library)) = line.split_once("-lswift") {
            if !library.starts_with("Compatibility") {
                overlays.insert(format!("swift{}", library.trim()));
            }
        }
    }
    assert!(
        !overlays.is_empty(),
        "Swift object has no runtime autolinks"
    );
    for library in overlays {
        println!("cargo:rustc-link-arg=-Wl,-weak-l{library}");
    }
    true
}

fn xcrun(args: &[&str]) -> String {
    let output = Command::new("xcrun")
        .args(args)
        .output()
        .expect("run xcrun");
    assert!(
        output.status.success(),
        "xcrun failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout)
        .expect("xcrun output")
        .trim()
        .to_string()
}

fn embed_source_commit() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
        .expect("Cargo must provide the desktop manifest directory");
    let repository = Path::new(&manifest_dir).join("../..");
    let output = Command::new("git")
        .args(["rev-parse", "HEAD"])
        .current_dir(&repository)
        .output()
        .expect("the source-built desktop requires Git");
    let commit = String::from_utf8(output.stdout)
        .expect("Git returned a non-UTF-8 source commit")
        .trim()
        .to_string();
    if !output.status.success()
        || commit.len() != 40
        || !commit
            .bytes()
            .all(|byte| byte.is_ascii_digit() || matches!(byte, b'a'..=b'f'))
    {
        panic!("the source-built desktop requires one exact lowercase Git commit");
    }
    println!("cargo:rustc-env=RCP_DESKTOP_SOURCE_COMMIT={commit}");
    println!("cargo:rerun-if-changed=build.rs");

    let mut git_paths = vec!["HEAD".to_string(), "packed-refs".to_string()];
    let symbolic_ref = Command::new("git")
        .args(["symbolic-ref", "-q", "HEAD"])
        .current_dir(&repository)
        .output()
        .expect("the source-built desktop requires Git metadata");
    if symbolic_ref.status.success() {
        git_paths.push(
            String::from_utf8(symbolic_ref.stdout)
                .expect("Git returned a non-UTF-8 source ref")
                .trim()
                .to_string(),
        );
    }
    for git_path in git_paths {
        let path = Command::new("git")
            .args(["rev-parse", "--git-path", &git_path])
            .current_dir(&repository)
            .output()
            .expect("the source-built desktop requires Git metadata");
        if path.status.success() {
            let path = String::from_utf8(path.stdout)
                .expect("Git returned a non-UTF-8 metadata path")
                .trim()
                .to_string();
            println!("cargo:rerun-if-changed={path}");
        }
    }
}
