/// The RCP window loads the backend's own origin, which the ACL treats as remote,
/// so every app command needs an autogenerated permission the capability can grant.
const COMMANDS: &[&str] = &[
    "desktop_status",
    "desktop_reconnect_backend",
    "desktop_show_ready",
    "open_artifact_preview",
    "download_artifact",
    "open_external",
    "request_quit",
    "check_for_update",
    "apply_update",
];

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("failed to run tauri-build");
}
