"""Resource bounds for supervisor operations."""

from __future__ import annotations

HTTP_TIMEOUT_SECONDS = 15
FETCH_TIMEOUT_SECONDS = 300
MAX_REDIRECTS = 5
DOWNLOAD_CHUNK_BYTES = 64 * 1024
MAX_RELEASE_METADATA_BYTES = 4 * 1024 * 1024
MAX_MANIFEST_BYTES = 64 * 1024
MAX_LOCK_BYTES = 16 * 1024 * 1024
MAX_WHEEL_BYTES = 256 * 1024 * 1024
MAX_WHEEL_METADATA_BYTES = 1024 * 1024
MAX_WHEEL_MEMBERS = 20_000
MAX_SELECTED_RECEIPT_BYTES = 16 * 1024
MAX_UNPACKED_WHEEL_BYTES = 1024 * 1024 * 1024
INSTALL_TIMEOUT_SECONDS = 900
IDENTITY_TIMEOUT_SECONDS = 30
CHECKPOINT_SPACE_MARGIN = 1.1
MAX_INSTALLED_RUNTIME_BYTES = 1024**4
MAX_INSTALLED_RUNTIME_ENTRIES = 100_000
# Retained artifacts a committed update leaves behind. No checkpoint: a committed
# update never restores old data, so every snapshot and failed attempt's
# quarantine is removed. Two release trees cover the live release and the
# previous one. Preparation and pruning are serialized, so unrecorded failed
# workspaces can be removed at the next successful operation.
RETAINED_CHECKPOINTS = 0
RETAINED_RELEASES = 2
RETAINED_OPERATION_JOURNALS = 20
RETAINED_SUPERVISOR_LOGS = 20
RETAINED_ROOT_ENVIRONMENTS = 2
MAX_OPERATION_BYTES = 1024 * 1024
APP_COMMAND_TIMEOUT_SECONDS = 300
# An update drains running agent turns for up to two hours before refusing.
MAINTENANCE_TIMEOUT_SECONDS = 2 * 60 * 60
# Startup recovery waits this long for a running protected backup to finish.
DEPLOYMENT_LOCK_TIMEOUT_SECONDS = 30 * 60
SERVICE_TIMEOUT_SECONDS = 90
STARTUP_RECOVERY_TIMEOUT_SECONDS = 3600
PROBE_TIMEOUT_SECONDS = 120
MAX_APP_OUTPUT_BYTES = 8 * 1024 * 1024
CONTROL_MAX_RESPONSE_BYTES = 262144
CONTROL_MAX_ERROR_CODE_CHARS = 64
CONTROL_MAX_ERROR_MESSAGE_CHARS = 240
MAX_DIAGNOSTIC_CHARS = 2048

LEGACY_START_POLL_SECONDS = 0.1
RESTORE_TIMEOUT_SECONDS = 1800
MAX_RESTORE_ARCHIVE_BYTES = 1024**4
MAX_RESTORE_PROGRESS_STEPS = 4000
MAX_RESTORE_PROGRESS_BYTES = 4 * 1024 * 1024
ROOT_EXECUTABLE_PATH = "/usr/bin:/bin:/usr/local/bin"
# Same bound as the application wizard: extra fields point at --machine-readable.
INTERACTIVE_FIELD_LIMIT = 8
